import { useMemo, useState } from "react";
import { buildSelectableDiff, compareText } from "../utils";

// AI 修改前后对比弹窗（自 main.tsx 拆分）
export function SelectionDiffModal({ before, after, onClose, onApply }: { before: string; after: string; onClose: () => void; onApply: (replacement?: string | React.MouseEvent) => void }) {
  const diff = useMemo(() => compareText(before, after), [before, after]);
  const selectable = useMemo(() => buildSelectableDiff(before, after), [before, after]);
  const changedIndexes = selectable.map((item, index) => item.changed ? index : -1).filter((index) => index >= 0);
  const [accepted, setAccepted] = useState<Set<number>>(() => new Set(changedIndexes));
  const replacement = selectable.map((item, index) => item.changed && accepted.has(index) ? item.after : item.before).join("");
  return <div className="modal-backdrop priority-modal" role="presentation"><section className="modal-card selection-diff-modal" role="dialog" aria-modal="true" aria-label="AI 修改对比"><div className="section-heading"><div><p className="eyebrow">AI 建议</p><h2>修改前后对比</h2></div><button type="button" className="text-button" onClick={onClose}>关闭</button></div><p className="hint">每一处绿色建议均可单独选用；未勾选的地方会保留原文。</p><div className="selection-diff-columns"><section><h3>修改前</h3><pre>{selectable.map((item, index) => <span className={item.changed ? "diff-removed" : ""} key={index}>{item.before}</span>)}</pre></section><section><h3>修改后</h3><pre>{selectable.map((item, index) => item.changed ? <label className="diff-choice" key={index}><input type="checkbox" checked={accepted.has(index)} onChange={(event) => setAccepted((current) => { const next = new Set(current); if (event.target.checked) next.add(index); else next.delete(index); return next; })} /><span className="diff-added">{item.after || "（删除此处）"}</span></label> : <span key={index}>{item.after}</span>)}</pre></section></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setAccepted(new Set(changedIndexes))}>全选建议</button><button type="button" className="secondary-button" onClick={onClose}>取消</button><button type="button" onClick={() => onApply(replacement)}>应用已选 {accepted.size} 处</button></div></section></div>;
  return <div className="modal-backdrop priority-modal" role="presentation"><section className="modal-card selection-diff-modal" role="dialog" aria-modal="true" aria-label="AI 修改对比"><div className="section-heading"><div><p className="eyebrow">AI 建议</p><h2>修改前后对比</h2></div><button type="button" className="text-button" onClick={onClose}>关闭</button></div><p className="hint">红色表示将被替换的原文，绿色表示 AI 建议新增或改写的内容。未着色部分保持一致。</p><div className="selection-diff-columns"><section><h3>修改前</h3><pre>{diff.before.map((segment, index) => <span className={segment.changed ? "diff-removed" : ""} key={index}>{segment.value}</span>)}</pre></section><section><h3>修改后</h3><pre>{diff.after.map((segment, index) => <span className={segment.changed ? "diff-added" : ""} key={index}>{segment.value}</span>)}</pre></section></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>继续查看</button><button type="button" onClick={onApply}>采用右侧建议</button></div></section></div>;
}

