import type { FastifyInstance } from "fastify";
import type { AppDatabase } from "../db/database";
import type { AccountRepository } from "../accounts/account-repository";
import type { ContentSourceService } from "../content/content-source-service";
import type { ContentProjectRepository } from "../content/content-project-repository";
import type { ContentBriefRepository } from "../content/content-brief-repository";
import type { ContentOutlineRepository } from "../content/content-outline-repository";
import type { ContentDraftRepository } from "../content/content-draft-repository";
import type { ContentResearchRepository } from "../content/content-research-repository";
import type { ContentReviewRepository } from "../content/content-review-repository";
import type { LocalAssetStore } from "../content/local-asset-store";
import type { RemoteImageImportService } from "../content/remote-image-import-service";
import type { AiContentService } from "../ai/ai-content-service";
import type { AiAuditLog } from "../ai/ai-audit-log";
import type { CredentialVault } from "../security/credential-vault";
import type { ModelProvider } from "../ai/model-provider";
import type { WechatPublishingService } from "../wechat/wechat-publishing-service";
import type { WechatCallbackService } from "../wechat/wechat-callback-service";
import type { AppCredentialRepository } from "../security/app-credential-repository";
import type { ModelConnectionRepository } from "../ai/model-connection-repository";
import type { SkillRegistry } from "../skills/skill-registry";
import type { CoverGenerationService } from "../content/modelscope-cover-service";
import type { CsdnChannelService } from "../csdn/csdn-channel-service";
import type { CnblogsChannelService } from "../cnblogs/cnblogs-channel-service";
import type { JuejinChannelService } from "../juejin/juejin-channel-service";
import type { FiftyoneCtoChannelService } from "../fiftyone-cto/fiftyone-cto-channel-service";
import type { CsdnBrowserConfirmResult } from "./schemas";

/** 组装本地 API 服务所需的所有依赖，供各路由模块解构使用。 */
export interface ServerContext {
  server: FastifyInstance;
  startedAt: string;
  logFilePath?: string;
  csdnBrowserConfirm?: (jobId: string) => Promise<CsdnBrowserConfirmResult | null>;
  database: AppDatabase;
  vault: CredentialVault;
  modelProvider: ModelProvider;
  assetStore?: LocalAssetStore;
  accounts: AccountRepository;
  contentSources: ContentSourceService;
  contentProjects: ContentProjectRepository;
  contentBriefs: ContentBriefRepository;
  contentOutlines: ContentOutlineRepository;
  contentDrafts: ContentDraftRepository;
  contentResearch: ContentResearchRepository;
  contentReviews: ContentReviewRepository;
  remoteImages: RemoteImageImportService;
  wechat: WechatPublishingService;
  wechatCallbacks: WechatCallbackService;
  appCredentials: AppCredentialRepository;
  getTavilyApiKey: () => string | undefined;
  getResearchProxyUrl: () => string;
  modelConnections: ModelConnectionRepository;
  skills?: SkillRegistry;
  aiAuditLog?: AiAuditLog;
  effectiveModelProvider: ModelProvider;
  aiContent: AiContentService;
  csdnChannels: CsdnChannelService;
  cnblogsChannels: CnblogsChannelService;
  juejinChannels: JuejinChannelService;
  fiftyoneCtoChannels: FiftyoneCtoChannelService;
  coverGenerator: CoverGenerationService;
}
